services:
  webapi:
    build:
      context: ./CloudServiceStore
      dockerfile: Dockerfile
    container_name: cloudservicestore_api
    ports:
      - "5053:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CloudServiceStoreDb;User Id=sa;Password=Your_Strong_Password_123!;TrustServerCertificate=True;
      - Vps__DefaultImage=vps-demo-image
      - Cache__Enabled=true
      - Cache__RedisConnectionString=redis:6379
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SenderEmail=buidi7170@gmail.com
      - EmailSettings__SenderPassword=${EMAIL_SENDER_PASSWORD:-acmbfwjvytdzwnys}
      - EmailSettings__SenderName=${EMAIL_SENDER_NAME:-CloudHost VN}
      - Frontend__BaseUrl=${FRONTEND_BASE_URL:-https://your-domain.com} # Đọc từ biến môi trường trên VPS, nếu không có sẽ lấy mặc định
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./CloudServiceStore/images:/app/images
    depends_on:
      - sqlserver
      - redis
    restart: unless-stopped
    mem_limit: 512m

  vps-demo-image:
    build:
      context: ./CloudServiceStore/docker/vps-demo-image
    image: vps-demo-image
    profiles:
      - build

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudservicestore_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_Strong_Password_123!
      - MSSQL_MEMORY_LIMIT_MB=1024
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    mem_limit: 1536m

  redis:
    image: redis:7-alpine
    container_name: cloudservicestore_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    mem_limit: 256m

volumes:
  sqlserver_data:
