services:
  webapi:
    image: ghcr.io/buidi2004/cloudservicestore-webapi:latest
    build:
      context: ./CloudServiceStore
      dockerfile: Dockerfile
    container_name: cloudservicestore_api
    ports:
      - "5053:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CloudServiceStoreDb;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;
      - Vps__DefaultImage=vps-demo-image
      - Cache__Enabled=true
      - Cache__RedisConnectionString=redis:6379
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SenderEmail=${EMAIL_SENDER_EMAIL:-buidi7170@gmail.com}
      - EmailSettings__SenderPassword=${EMAIL_SENDER_PASSWORD}
      - EmailSettings__SenderName=${EMAIL_SENDER_NAME:-CloudHost VN}
      - Frontend__BaseUrl=${FRONTEND_BASE_URL:-https://your-domain.com} # Đọc từ biến môi trường trên VPS, nếu không có sẽ lấy mặc định
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=${MINIO_ROOT_USER:-minioadmin}
      - MinIO__SecretKey=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MinIO__UseSSL=false
      - Provisioning__PortRangeStart=30000
      - Provisioning__PortRangeEnd=40000
      - Provisioning__TimeoutSeconds=60
      - Provisioning__DataPath=/app/provisioning-data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./CloudServiceStore/images:/app/images
      - provisioning_data:/app/provisioning-data
    depends_on:
      - sqlserver
      - redis
      - minio
    restart: unless-stopped
    mem_limit: 512m

  vps-demo-image:
    build:
      context: ./CloudServiceStore/docker/vps-demo-image
    image: vps-demo-image
    profiles:
      - build

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudservicestore_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_MEMORY_LIMIT_MB=1024
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    mem_limit: 1536m

  redis:
    image: redis:7-alpine
    container_name: cloudservicestore_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    mem_limit: 256m

  minio:
    image: minio/minio:latest
    container_name: cloudservicestore_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    mem_limit: 512m

volumes:
  sqlserver_data:
  minio_data:
  provisioning_data:
